export enum ApiEnum {
  ERROR = 0,
  Log = "log",
  Error = "error",
  Warn = "warn",
  Info = "info",
  MOCK_MANY_NOTIFICATIONS = 98,
  GetFileList = 100,
  GetFileDetailList = 101,
  PostCommit = 102,
  GetCommitDetail = 103,
  GetCommitList = 104,
  GetFileDetail = 105,
  Restore = 106,
}
