version: "1.0.0"
services:
  dev:
    build:
      context: .
      dockerfile: ./service/dev/Dockerfile
    ports:
      - "8022:22"
    command: ["/bin/bash"]
    tty: true
    stdin_open: true
    volumes:
      - .:/app
  build:
    build:
      context: .
      dockerfile: ./service/build/Dockerfile
    ports:
      - "8022:22"
    command: ["/bin/bash"]
    tty: true
    stdin_open: true
    volumes:
      - .:/app